# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#   - run: mv .env.kutai .env
#     - run: npm i cross-env
#     - run: npm run build-prod --if-present
    
    - name: 📂 Sync files
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --exclude=".git" --exclude=".github"
        path: /
        remote_path: /usr/share/nginx/www/anak
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.PRIVATE_KEY }}
        
    - name: deploy use ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        key:  ${{ secrets.PRIVATE_KEY }}
        username: ${{ secrets.username }}
        port: 22
        script: | 
          cd /usr/share/nginx/www/anak
          sudo chmod -R 777 storage 
          php74 composer.phar install
#          git pull origin master
#          git status
          
    - name: send notif telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Push and Build Simdik kutai Backend
